from __future__ import annotations

import argparse
from pathlib import Path

from shared import DATA_ROOT, PipelineState, compute_path_signature, detect_default_weights_root

from .nuextract_extractor import (
    DEFAULT_NUEXTRACT_MODEL,
    DEFAULT_NUEXTRACT_VARIANT,
    NUEXTRACT_MODEL_VARIANTS,
    NuExtractExtractor,
)
from .pipeline import ChapterFeaturePipeline
from .processor import discover_processed_books, load_json, process_and_write_book_dir, resolve_feature_output_dir


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="part2-run",
        description="Run chapter-level feature extraction from Yggdrasil derived chapters using NuExtract.",
    )
    parser.add_argument("input", help="Input Yggdrasil/derived/chapters root or one processed book directory.")
    parser.add_argument(
        "-o",
        "--output",
        help=f"Output root directory. Defaults to {DATA_ROOT / 'derived' / 'features'}.",
    )
    parser.add_argument(
        "--weights-root",
        default=str(detect_default_weights_root()),
        help="Local weights root directory. Defaults to ./models/weights when populated, with legacy fallback.",
    )
    parser.add_argument(
        "--nuextract-model",
        default="",
        help="NuExtract model name or local path. When omitted, the --nuextract-size variant directory is used.",
    )
    parser.add_argument(
        "--nuextract-size",
        choices=sorted(NUEXTRACT_MODEL_VARIANTS.keys()),
        default=DEFAULT_NUEXTRACT_VARIANT,
        help="NuExtract model variant loaded from models/weights, e.g. NuExtract_2B, NuExtract_4B, or NuExtract_8B.",
    )
    parser.add_argument(
        "--nuextract-max-input-chars",
        type=int,
        default=6000,
        help="Maximum chapter characters sent to NuExtract.",
    )
    parser.add_argument(
        "--nuextract-max-new-tokens",
        type=int,
        default=320,
        help="Maximum new tokens generated by NuExtract.",
    )
    parser.add_argument(
        "--device-map",
        default="auto",
        help="Transformers device_map passed to NuExtract model loading.",
    )
    parser.add_argument(
        "--compact",
        action="store_true",
        help="Write compact JSON instead of pretty JSON.",
    )
    parser.add_argument(
        "--sync-state",
        dest="sync_state",
        action="store_true",
        default=True,
        help="Sync book/chapter progress into runs/pipeline_state/state.json. Enabled by default.",
    )
    parser.add_argument(
        "--no-sync-state",
        dest="sync_state",
        action="store_false",
        help="Do not write progress or chapter state into runs/pipeline_state/state.json for this run.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    nuextract_extractor = NuExtractExtractor(
        model_name=args.nuextract_model or NUEXTRACT_MODEL_VARIANTS[args.nuextract_size],
        model_variant=args.nuextract_size,
        weights_root=args.weights_root,
        max_input_chars=args.nuextract_max_input_chars,
        max_new_tokens=args.nuextract_max_new_tokens,
        device_map=args.device_map,
    )
    pipeline = ChapterFeaturePipeline(
        nuextract_extractor=nuextract_extractor,
    )

    pretty = not args.compact
    books = discover_processed_books(args.input)
    written_dirs: list[Path] = []
    state = PipelineState() if args.sync_state else None
    if state is not None:
        state.begin_run("softmodel", total_candidates=len(books))

    try:
        for book_dir in books:
            index_payload = load_json(Path(book_dir) / "index.json")
            source_book_path = index_payload["book_metadata"]["source_path"]
            raw_source_signature = compute_path_signature(source_book_path) if Path(source_book_path).exists() else ""
            processdata_signature = compute_path_signature(book_dir)
            output_dir = resolve_feature_output_dir({"index": index_payload}, output_root=args.output)
            if state is not None:
                should_skip, matched_book = state.should_skip_step(
                    step_name="softmodel",
                    source_path=source_book_path,
                    source_signature=processdata_signature,
                    output_path=output_dir,
                )
            else:
                should_skip, matched_book = False, None

            if should_skip and matched_book is not None and state is not None:
                state.increment_run_counter("softmodel", "skipped")
                print(
                    f"[SKIP] {book_dir} -> {output_dir} "
                    f"(index={matched_book.get('index', 'unknown')})"
                )
                continue

            if state is not None:
                book_record, is_new_book = state.get_or_create_book(
                    source_path=source_book_path,
                    source_signature=raw_source_signature or processdata_signature,
                    update_source_signature=bool(raw_source_signature),
                )
            else:
                book_record, is_new_book = None, False
            try:
                output_dir = process_and_write_book_dir(
                    book_dir,
                    pipeline=pipeline,
                    output_root=args.output,
                    pretty=pretty,
                    state=state,
                    book_record=book_record,
                )
                written_dirs.append(output_dir)
                if state is not None and book_record is not None:
                    state.record_step(
                        step_name="softmodel",
                        book=book_record,
                        source_signature=processdata_signature,
                        status="completed",
                        output_path=output_dir,
                        params={
                            "nuextract_model": nuextract_extractor.requested_model_name,
                            "nuextract_size": nuextract_extractor.model_variant,
                            "nuextract_max_input_chars": nuextract_extractor.max_input_chars,
                            "nuextract_max_new_tokens": nuextract_extractor.max_new_tokens,
                            "device_map": nuextract_extractor.device_map,
                        },
                        metadata={
                            "book_id": index_payload["book_metadata"]["book_id"],
                            "book_index": book_record["index"],
                            "chapter_count": index_payload["book_metadata"].get("chapter_count", 0),
                        },
                    )
                    state.increment_run_counter("softmodel", "processed")
                print(
                    f"[OK] {book_dir} -> {output_dir} "
                    f"(index={book_record['index'] if book_record is not None else 'no-state'}, {'new' if is_new_book else 'updated'})"
                )
            except Exception as exc:
                if state is not None and book_record is not None:
                    state.record_step(
                        step_name="softmodel",
                        book=book_record,
                        source_signature=processdata_signature,
                        status="failed",
                        output_path=output_dir,
                        params={
                            "nuextract_model": nuextract_extractor.requested_model_name,
                            "nuextract_size": nuextract_extractor.model_variant,
                            "nuextract_max_input_chars": nuextract_extractor.max_input_chars,
                            "nuextract_max_new_tokens": nuextract_extractor.max_new_tokens,
                            "device_map": nuextract_extractor.device_map,
                        },
                        metadata={
                            "book_index": book_record["index"],
                        },
                        error=str(exc),
                    )
                    state.increment_run_counter("softmodel", "failed")
                raise
    finally:
        if state is not None:
            state.finish_run("softmodel")

    run_stats = state.run_stats("softmodel") if state is not None else {}
    print(
        f"Finished. Wrote {len(written_dirs)} feature book folder(s). "
        f"processed={run_stats.get('processed', 0)} "
        f"skipped={run_stats.get('skipped', 0)} "
        f"failed={run_stats.get('failed', 0)} "
        f"tracker={state.path if state is not None else 'disabled'}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
