from __future__ import annotations

import argparse
from pathlib import Path

from shared import (
    FACT_CHAPTER_FEATURES_ROOT,
    FACT_CLEANED_CHAPTERS_ROOT,
    PipelineState,
    compute_path_signature,
    detect_default_weights_root,
)
from shared.stage_queue import (
    NEGATIVE_BOOKS_PATH,
    mark_stage_done,
    registry_ordered_book_dirs,
    stage_is_done,
)

from .nuextract_extractor import (
    DEFAULT_NUEXTRACT_MODEL,
    DEFAULT_NUEXTRACT_VARIANT,
    NUEXTRACT_MODEL_VARIANTS,
    NuExtractExtractor,
)
from .pipeline import DEFAULT_CHAPTER_BATCH_SIZE, ChapterFeaturePipeline
from .processor import (
    discover_processed_books,
    feature_book_index_complete,
    load_json,
    process_and_write_book_dir,
    resolve_feature_output_dir,
)
from .unitizer import UnitizerConfig


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="part2-run",
        description="Run chapter-level feature extraction from TaciturnRaw cleaned novels using NuExtract.",
    )
    parser.add_argument(
        "input",
        help=f"Input {FACT_CLEANED_CHAPTERS_ROOT} root or one processed book directory.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help=f"Output root directory. Defaults to {FACT_CHAPTER_FEATURES_ROOT}.",
    )
    parser.add_argument(
        "--priority-book",
        action="append",
        default=[],
        help=(
            "Book key to run before the size-sorted auto queue. May be repeated. "
            "Accepted keys include clean slug/book_XXXX, clean id, title, raw slug, identity key, or source URL."
        ),
    )
    parser.add_argument(
        "--priority-file",
        help=(
            "Optional priority book list. Defaults to Library/indexes/priority_books.txt. "
            "Use an empty/nonexistent path to rely only on --priority-book."
        ),
    )
    parser.add_argument(
        "--negative-book",
        action="append",
        default=[],
        help=(
            "Book key to skip for this softmodel run. May be repeated. "
            "Accepted keys match --priority-book."
        ),
    )
    parser.add_argument(
        "--negative-file",
        default=str(NEGATIVE_BOOKS_PATH),
        help="Optional negative book list. Defaults to Library/indexes/negative_books.txt.",
    )
    parser.add_argument(
        "--weights-root",
        default=str(detect_default_weights_root()),
        help="Local weights root directory. Defaults to ./models/weights when populated, with legacy fallback.",
    )
    parser.add_argument(
        "--nuextract-model",
        default="",
        help="NuExtract model name or local path. When omitted, the --nuextract-size variant directory is used.",
    )
    parser.add_argument(
        "--nuextract-size",
        choices=sorted(NUEXTRACT_MODEL_VARIANTS.keys()),
        default=DEFAULT_NUEXTRACT_VARIANT,
        help="NuExtract model variant loaded from models/weights, e.g. NuExtract_2B, NuExtract_4B, or NuExtract_8B.",
    )
    parser.add_argument(
        "--nuextract-max-input-chars",
        type=int,
        default=6000,
        help="Maximum chapter characters sent to NuExtract.",
    )
    parser.add_argument(
        "--nuextract-max-new-tokens",
        type=int,
        default=768,
        help="Maximum new tokens generated by NuExtract.",
    )
    parser.add_argument(
        "--device-map",
        default="auto",
        help="Transformers device_map passed to NuExtract model loading.",
    )
    parser.add_argument(
        "--inference-backend",
        choices=["auto", "transformers", "vllm"],
        default="vllm",
        help="NuExtract inference runtime. Defaults to vLLM for NuExtract_8B.",
    )
    parser.add_argument(
        "--vllm-tensor-parallel-size",
        type=int,
        default=1,
        help="vLLM tensor parallel size.",
    )
    parser.add_argument(
        "--vllm-gpu-memory-utilization",
        type=float,
        default=0.85,
        help="vLLM GPU memory utilization fraction.",
    )
    parser.add_argument(
        "--vllm-max-model-len",
        type=int,
        default=8192,
        help="vLLM max model length used to size KV cache.",
    )
    parser.add_argument(
        "--vllm-max-num-seqs",
        type=int,
        default=None,
        help="Maximum number of concurrent vLLM sequences. Lower this when sharing a GPU.",
    )
    parser.add_argument(
        "--vllm-generate-batch-size",
        type=int,
        default=16,
        help="Maximum prompts sent to one vLLM generate() call. Use 0 to disable chunking.",
    )
    parser.add_argument(
        "--vllm-enforce-eager",
        action="store_true",
        help="Enable eager mode in vLLM to reduce compile overhead at the cost of some throughput.",
    )
    parser.add_argument(
        "--compact",
        action="store_true",
        help="Write compact JSON instead of pretty JSON.",
    )
    parser.add_argument(
        "--chapter-batch-size",
        type=int,
        default=DEFAULT_CHAPTER_BATCH_SIZE,
        help=f"How many chapters to batch together per vLLM extraction step. Default: {DEFAULT_CHAPTER_BATCH_SIZE}.",
    )
    parser.add_argument(
        "--unitize-long-chapters",
        dest="unitize_long_chapters",
        action="store_true",
        default=True,
        help="Split long chapters into narrative units before softmodel feature extraction. Enabled by default.",
    )
    parser.add_argument(
        "--no-unitize-long-chapters",
        dest="unitize_long_chapters",
        action="store_false",
        help="Disable long-chapter narrative unit splitting.",
    )
    parser.add_argument(
        "--unitizer-target-chars",
        type=int,
        default=6500,
        help="Target narrative unit size in Chinese characters.",
    )
    parser.add_argument(
        "--unitizer-hard-max-chars",
        type=int,
        default=10000,
        help="Hard maximum narrative unit size before forced punctuation splitting.",
    )
    parser.add_argument(
        "--unitizer-suggest-chars",
        type=int,
        default=8000,
        help="Chapter size above which splitting is suggested.",
    )
    parser.add_argument(
        "--unitizer-required-chars",
        type=int,
        default=12000,
        help="Chapter size above which splitting is required.",
    )
    parser.add_argument(
        "--unitizer-force-multi-chars",
        type=int,
        default=20000,
        help="Chapter size above which multiple units are strongly forced.",
    )
    parser.add_argument(
        "--index-flush-interval",
        type=int,
        default=None,
        help=(
            "Flush novels_chapter/<book>/index.json every N chapter decisions. "
            "Defaults to --chapter-batch-size, so completed batches are resumable."
        ),
    )
    parser.add_argument(
        "--state-save-interval",
        type=int,
        default=100,
        help=(
            "Flush runs/pipeline_state/state.json every N chapter decisions. "
            "Use 0 to disable intra-book state flushes. Existing chapter output files are still used for resume."
        ),
    )
    parser.add_argument(
        "--sync-state",
        dest="sync_state",
        action="store_true",
        default=False,
        help="Sync book/chapter progress into runs/pipeline_state/state.json. Disabled by default for long softmodel runs.",
    )
    parser.add_argument(
        "--no-sync-state",
        dest="sync_state",
        action="store_false",
        help="Do not write progress or chapter state into runs/pipeline_state/state.json for this run. This is the default.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    nuextract_extractor = NuExtractExtractor(
        model_name=args.nuextract_model or NUEXTRACT_MODEL_VARIANTS[args.nuextract_size],
        model_variant=args.nuextract_size,
        weights_root=args.weights_root,
        max_input_chars=args.nuextract_max_input_chars,
        max_new_tokens=args.nuextract_max_new_tokens,
        device_map=args.device_map,
        inference_backend=args.inference_backend,
        vllm_tensor_parallel_size=args.vllm_tensor_parallel_size,
        vllm_gpu_memory_utilization=args.vllm_gpu_memory_utilization,
        vllm_max_model_len=args.vllm_max_model_len,
        vllm_max_num_seqs=args.vllm_max_num_seqs,
        vllm_generate_batch_size=args.vllm_generate_batch_size,
        vllm_enforce_eager=args.vllm_enforce_eager,
    )
    pipeline = ChapterFeaturePipeline(
        nuextract_extractor=nuextract_extractor,
        chapter_batch_size=args.chapter_batch_size,
    )
    unitizer_config = UnitizerConfig(
        enabled=args.unitize_long_chapters,
        chapter_split_suggest_chars=args.unitizer_suggest_chars,
        chapter_split_required_chars=args.unitizer_required_chars,
        chapter_force_multi_chars=args.unitizer_force_multi_chars,
        target_unit_chars=args.unitizer_target_chars,
        hard_max_unit_chars=args.unitizer_hard_max_chars,
    )

    pretty = not args.compact
    queue_result = registry_ordered_book_dirs(
        args.input,
        source_stage="cleaned_chapters",
        output_root=args.output or FACT_CHAPTER_FEATURES_ROOT,
        output_stage="softmodel",
        priority_path=args.priority_file,
        priority_keys=args.priority_book,
        negative_path=args.negative_file,
        negative_keys=args.negative_book,
    )
    if queue_result is None:
        books = discover_processed_books(args.input)
    else:
        books, queue_stats = queue_result
        print(
            f"[QUEUE] registry={queue_stats.source} queued={queue_stats.queued} "
            f"curated={queue_stats.curated} done={queue_stats.skipped_done} "
            f"missing_source={queue_stats.skipped_missing_source} "
            f"incomplete={queue_stats.skipped_incomplete} "
            f"negative={queue_stats.skipped_negative} "
            f"chapter_range={queue_stats.skipped_chapter_range}"
        )
    written_dirs: list[Path] = []
    local_stats = {"processed": 0, "skipped": 0, "failed": 0}
    state = PipelineState() if args.sync_state else None
    if state is not None:
        state.begin_run("softmodel", total_candidates=len(books))

    try:
        for book_dir in books:
            index_payload = load_json(Path(book_dir) / "index.json")
            source_book_path = index_payload["book_metadata"]["source_path"]
            output_dir = resolve_feature_output_dir({"index": index_payload}, output_root=args.output)
            if stage_is_done(output_dir, "softmodel"):
                local_stats["skipped"] += 1
                if state is not None:
                    state.increment_run_counter("softmodel", "skipped")
                print(f"[SKIP] {book_dir} -> {output_dir} (done-file)")
                continue
            if feature_book_index_complete(book_dir, output_dir):
                mark_stage_done(
                    output_dir,
                    "softmodel",
                    metadata={
                        "book_id": index_payload["book_metadata"].get("book_id", ""),
                        "chapter_count": index_payload["book_metadata"].get("chapter_count", 0),
                        "source": "feature-index",
                    },
                )
                local_stats["skipped"] += 1
                if state is not None:
                    state.increment_run_counter("softmodel", "skipped")
                print(f"[SKIP] {book_dir} -> {output_dir} (feature-index)")
                continue

            if state is not None:
                raw_source_signature = compute_path_signature(source_book_path) if Path(source_book_path).exists() else ""
                processdata_signature = compute_path_signature(book_dir)
                should_skip, matched_book = state.should_skip_step(
                    step_name="softmodel",
                    source_path=source_book_path,
                    source_signature=processdata_signature,
                    output_path=output_dir,
                )
            else:
                should_skip, matched_book = False, None
                raw_source_signature = ""
                processdata_signature = ""

            if should_skip and matched_book is not None and state is not None:
                local_stats["skipped"] += 1
                state.increment_run_counter("softmodel", "skipped")
                state.save()
                print(
                    f"[SKIP] {book_dir} -> {output_dir} "
                    f"(index={matched_book.get('index', 'unknown')})"
                )
                continue

            if state is not None:
                book_record, is_new_book = state.get_or_create_book(
                    source_path=source_book_path,
                    source_signature=raw_source_signature or processdata_signature,
                    update_source_signature=bool(raw_source_signature),
                )
            else:
                book_record, is_new_book = None, False
            try:
                output_dir = process_and_write_book_dir(
                    book_dir,
                    pipeline=pipeline,
                output_root=args.output,
                pretty=pretty,
                state=state,
                book_record=book_record,
                state_save_interval=args.state_save_interval,
                index_flush_interval=args.index_flush_interval,
                unitizer_config=unitizer_config,
            )
                written_dirs.append(output_dir)
                mark_stage_done(
                    output_dir,
                    "softmodel",
                    metadata={
                        "book_id": index_payload["book_metadata"].get("book_id", ""),
                        "chapter_count": index_payload["book_metadata"].get("chapter_count", 0),
                    },
                )
                local_stats["processed"] += 1
                if state is not None and book_record is not None:
                    state.record_step(
                        step_name="softmodel",
                        book=book_record,
                        source_signature=processdata_signature,
                        status="completed",
                        output_path=output_dir,
                        params={
                            "nuextract_model": nuextract_extractor.requested_model_name,
                            "nuextract_size": nuextract_extractor.model_variant,
                            "nuextract_max_input_chars": nuextract_extractor.max_input_chars,
                            "nuextract_max_new_tokens": nuextract_extractor.max_new_tokens,
                            "inference_backend": nuextract_extractor.inference_backend,
                            "vllm_tensor_parallel_size": nuextract_extractor.vllm_tensor_parallel_size,
                            "vllm_gpu_memory_utilization": nuextract_extractor.vllm_gpu_memory_utilization,
                            "vllm_max_model_len": nuextract_extractor.vllm_max_model_len,
                            "vllm_max_num_seqs": nuextract_extractor.vllm_max_num_seqs,
                            "vllm_generate_batch_size": nuextract_extractor.vllm_generate_batch_size,
                            "vllm_enforce_eager": nuextract_extractor.vllm_enforce_eager,
                            "device_map": nuextract_extractor.device_map,
                        },
                        metadata={
                            "book_id": index_payload["book_metadata"]["book_id"],
                            "book_index": book_record["index"],
                            "chapter_count": index_payload["book_metadata"].get("chapter_count", 0),
                        },
                    )
                    state.increment_run_counter("softmodel", "processed")
                    state.save()
                print(
                    f"[OK] {book_dir} -> {output_dir} "
                    f"(index={book_record['index'] if book_record is not None else 'no-state'}, {'new' if is_new_book else 'updated'})"
                )
            except Exception as exc:
                if state is not None and book_record is not None:
                    state.record_step(
                        step_name="softmodel",
                        book=book_record,
                        source_signature=processdata_signature,
                        status="failed",
                        output_path=output_dir,
                        params={
                            "nuextract_model": nuextract_extractor.requested_model_name,
                            "nuextract_size": nuextract_extractor.model_variant,
                            "nuextract_max_input_chars": nuextract_extractor.max_input_chars,
                            "nuextract_max_new_tokens": nuextract_extractor.max_new_tokens,
                            "inference_backend": nuextract_extractor.inference_backend,
                            "vllm_tensor_parallel_size": nuextract_extractor.vllm_tensor_parallel_size,
                            "vllm_gpu_memory_utilization": nuextract_extractor.vllm_gpu_memory_utilization,
                            "vllm_max_model_len": nuextract_extractor.vllm_max_model_len,
                            "vllm_max_num_seqs": nuextract_extractor.vllm_max_num_seqs,
                            "vllm_generate_batch_size": nuextract_extractor.vllm_generate_batch_size,
                            "vllm_enforce_eager": nuextract_extractor.vllm_enforce_eager,
                            "device_map": nuextract_extractor.device_map,
                        },
                        metadata={
                            "book_index": book_record["index"],
                        },
                        error=str(exc),
                    )
                    state.increment_run_counter("softmodel", "failed")
                    state.save()
                local_stats["failed"] += 1
                raise
    finally:
        if state is not None:
            state.finish_run("softmodel")

    run_stats = state.run_stats("softmodel") if state is not None else local_stats
    print(
        f"Finished. Wrote {len(written_dirs)} feature book folder(s). "
        f"processed={run_stats.get('processed', 0)} "
        f"skipped={run_stats.get('skipped', 0)} "
        f"failed={run_stats.get('failed', 0)} "
        f"tracker={state.path if state is not None else 'disabled'}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
